services:
  cloudscaledb:
    container_name: CloudScaleDB
    image: postgres:17  # or pin to a specific version you want
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=CloudScaleDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_cloudscale:/var/lib/postgresql

volumes:
  postgres_cloudscale: